language: ruby
sudo: required
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

before_script:
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
  - mysql -e 'create database mmiworkshop_test'
  - psql -c 'create database mmiworkshop_test' -U postgres

script:
  - bundle exec rake -t db:schema:load
  - bundle exec rake -t db:test:prepare
  - bundle exec rake -t

after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"

bundler_args: --binstubs=./bundler_stubs
rvm:
  - 2.2.4
