# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50016e55c1a1436c7579b7170bcbe933abc5a94b8b7e3363d879f8f2f4e01f1b3494717e348dd013a1044aa50a25123dd27d67ee1c8e4c548bae84daf46a8a5e

test:
  secret_key_base: ab0ac28f74d81c4320d9f4a4e03250e0b6a68b9d195f61abe199e6dfbf2a4674484ff4f66654a13a17588784029ba1336ecfb9d7a64ad297924abb9c0672b55e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
